### ISSUE TITLE
does not support csproj with multiple target frameworks that target different versions of same package

### ISSUE THREAD

**Issue by BobbyCannon** [digitalcoyote/NuGetDefense#109]
**Describe the bug**
It seems that nugetdefense is having issues with multiple framework support in csproj that will target different versions of nuget packages depending on the framework used.

I think what is happening is a dictionary is used on package name. This is just a guess.

Example Snippet that would fail:

```
<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
	<PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
</ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
	<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
</ItemGroup>
<ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
	<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
</ItemGroup>
```

```
PS C:\Workspaces\GitHub\Speedy> nugetdefense.exe --project-file 'C:\Workspaces\GitHub\Speedy\Speedy.sln'
: Error : Encountered a fatal exception while checking for Dependencies in . Exception: System.ArgumentException: An item with the same key has already been added. Key: System.ComponentModel.Annotations
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at NuGetDefense.Core.NuGetFile.LoadPackages(String targetFramework, Boolean checkTransitiveDependencies, Boolean checkReferencedProjects)
   at NuGetDefense.Scanner.<>c__DisplayClass12_0.<LoadMultipleProjects>b__1(String m) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense.Lib/Scanner.cs:line 277
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at NuGetDefense.UtilityMethods.AddDistinctPackages(List`1 pkgs, IEnumerable`1 newPkgs) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense.Lib/UtilityMethods.cs:line 17
   at NuGetDefense.Scanner.LoadMultipleProjects(String TopLevelProject, IReadOnlyList`1 projects, Boolean specificFramework, String targetFramework, Boolean solutionFile) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense.Lib/Scanner.cs:line 277
   at NuGetDefense.Scanner.ScanVulnerabilities(ScanOptions options) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense.Lib/Scanner.cs:line 95
PS C:\Workspaces\GitHub\Speedy>
```

**To Reproduce**
1. pull the speedy repo at https://github.com/BobbyCannon/Speedy
2. run the tool against the solution or project
  a. ex. nugetdefense.exe --project-file 'C:\Workspaces\GitHub\Speedy\Speedy.sln'
3. Check exception

**Expected behavior**
I would expect the tool to check each version of each package and report on each one.

**Comment by digitalcoyote** [comment]
@BobbyCannon thanks for the detailed info. I'm also busy thanks to the holidays coming up, but I'll try to take a look at this soon if you don't get to it first.

**Comment by digitalcoyote** [comment]
Starting to slow down about for me, so I'm going to try to take a look at this this weekend.

**Comment by digitalcoyote** [comment]
Wife had plans I was unaware of, so I'm tackling a couple of older issues and I'll see about this one later in the week or this weekend.
