### ISSUE TITLE
Scanner crashes when encountering a SSIS project in a solution

### ISSUE THREAD

**Issue by jpboudreauforces** [digitalcoyote/NuGetDefense#131]
**Describe the bug**
When scanning a solution containing an SSIS project, the scanner crash because there is no PropertyGroup tag in the .dtproj.

It is the ByteDev.DotNetProject.Load that returns an "InvalidDotNetProjectException".

`: Error : Encountered a fatal exception while checking for Dependencies in . Exception: ByteDev.DotNet.Project.InvalidDotNetProjectException: Project document contains no PropertyGroup elements.
   at ByteDev.DotNet.Project.PropertyGroupCollection.GetPropertyGroups(XDocument xDocument)
   at ByteDev.DotNet.Project.PropertyGroupCollection..ctor(XDocument xDocument)
   at ByteDev.DotNet.Project.DotNetProject.SetPropertyGroupProperties(XDocument xDocument)
   at ByteDev.DotNet.Project.DotNetProject..ctor(XDocument xDocument)
   at ByteDev.DotNet.Project.DotNetProject.Load(String projFilePath)
   at NuGetDefense.Scanner.LoadMultipleProjects(String TopLevelProject, IReadOnlyList 1 projects, Boolean specificFramework, String targetFramework, Boolean solutionFile) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense.Lib/Scanner.cs:line 265
   at NuGetDefense.Scanner.ScanVulnerabilities(ScanOptions options) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense.Lib/Scanner.cs:line 95`

**To Reproduce**
1. Create a standard .net Framework Web App solution 
2. Add a SSIS project
3. Run nugetdefense -p solution.sln 
4. Notice the crash

**Expected behavior**
The scanner should ignore the project with no PropertyGroup and continue.

**Tools:**
 - IDE: VS2019, VS2022
 - OS: Windows 10

**Comment by digitalcoyote** [comment]
This should be a quick fix, but It'll be tomorrow before I get to work on it. I've not worked with SSIS projects before, I assume filtering them out by project file extension should work though.

**Comment by digitalcoyote** [comment]
This should be fixed in the v3.1.0 release
