### ISSUE TITLE
SqlLiteVulnerabilityCache TODO: Debug this query to make sure Vulnerable versions are input correctly

### ISSUE THREAD

**Issue by mabihz** [digitalcoyote/NuGetDefense#138]
**Describe the bug**
Exception on scanning:
packages.config: Error : Encountered a fatal exception while checking for Dependencies in packages.config. Exception: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at NuGetDefense.SqlLiteVulnerabilityCache.UpdateCache(Dictionary`2 reportedVulnerabilities, IEnumerable`1 updatedPkgs, String sourceName)
   at NuGetDefense.Scanner.ScanVulnerabilities(ScanOptions options)

**To Reproduce**
In my case, i did Scanner.Scan() with OSSIndex for a project using System.Security.Cryptography.Xml, which has vulnerabilities in that index. Other packages without vulnerabilities did not cause the exception, just that one with vulnerabilities.

**Expected behavior**
No exception should be thrown

**Additional context**
There is still a TODO in SqlLiteVulnerabilityCache in method UpdateCache, which may be the reason for that exception.

**Comment by digitalcoyote** [comment]
Was hoping to look at this tonight, but ended up working late. Hoping to look at this Monday now. Contributions welcome if anyone wants to work this before then.

**Comment by digitalcoyote** [comment]
I think I forgot to mark this resolved in one of the pre-releases. Going to try to confirm that today.
