### ISSUE TITLE
Intermittent exception from NuGetDefense.Core.NuGetFile.dotnetListPackages

### ISSUE THREAD

**Issue by a-teece** [digitalcoyote/NuGetDefense#182]
**Describe the bug**
On build servers we intermittently get an exception like the below. I suspect this is a threading issue due to use of BeginOutputReadLine; the string builder is still being written to after the process exists which conflicts with StringBuilder.ToString() which is not thread safe.
These SO threads are worth reading for context; https://stackoverflow.com/questions/12645351/stringbuilder-tostring-throw-an-index-out-of-range-exception and https://stackoverflow.com/questions/9533070/how-to-read-to-end-process-output-asynchronously-in-c

```
2024-04-23T14:00:04.2552692Z Skipping dotnet list package. No Packages found for C:\agent\_work\11\s\XXXXX\XXXXX.csproj.
2024-04-23T14:00:08.0791988Z : Error : Encountered a fatal exception while checking for Dependencies in . Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than or equal to the size of the collection. (Parameter 'chunkLength')
2024-04-23T14:00:08.0800965Z    at System.Text.StringBuilder.ToString()
2024-04-23T14:00:08.0810931Z    at NuGetDefense.Core.NuGetFile.dotnetListPackages(String projectFile, String targetFramework, Dictionary`2& projectectReferencePackages)
2024-04-23T14:00:08.0820121Z    at NuGetDefense.Core.NuGetFile.LoadPackages(String targetFramework, Boolean checkTransitiveDependencies, Boolean checkReferencedProjects)
2024-04-23T14:00:08.0828908Z    at NuGetDefense.Scanner.<>c__DisplayClass18_0.<LoadMultipleProjects>b__1(String m) in /home/codingcoyote/RiderProjects/NuGetDefense/Src/NuGetDefense.Lib/Scanner.cs:line 383
2024-04-23T14:00:08.0837833Z    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
2024-04-23T14:00:08.0846566Z    at NuGetDefense.UtilityMethods.AddDistinctPackages(List`1 pkgs, IEnumerable`1 newPkgs) in /home/codingcoyote/RiderProjects/NuGetDefense/Src/NuGetDefense.Lib/UtilityMethods.cs:line 17
2024-04-23T14:00:08.0854973Z    at NuGetDefense.Scanner.LoadMultipleProjects(String topLevelProject, IReadOnlyList`1 projects, Boolean specificFramework, String targetFramework, Boolean solutionFile) in /home/codingcoyote/RiderProjects/NuGetDefense/Src/NuGetDefense.Lib/Scanner.cs:line 383
2024-04-23T14:00:08.0862922Z    at NuGetDefense.Scanner.ScanVulnerabilities(ScanOptions options) in /home/codingcoyote/RiderProjects/NuGetDefense/Src/NuGetDefense.Lib/Scanner.cs:line 141
2024-04-23T14:00:08.2304166Z ##[error]Cmd.exe exited with code '-1'.
```

**To Reproduce**
Reproduction is intermittent. It probably occurs 1:10 for us. I suspect the core count and speed of the machine are a factor.

**Expected behavior**
No error

**Tools (please complete the following information):**
 - IDE: Azure DevOps Build Agent
 - OS: Windows Server 2022

**Comment by digitalcoyote** [comment]
I'm actually getting rid of that section of code altogether in favor of parsing the project.assets.json file.

I haven't had time to test it yet, but there is a pre release you can look at if you want to try the new logic. It should be a more stable method of checking anyway as non-english outputs have caused issues with parsing dotnet list in the past.

**Comment by a-teece** [comment]
Thanks for the tip. I'll take a look

**Comment by digitalcoyote** [comment]
I'm going to go ahead and work this. I'm a little embarrassed I overlooked this issue when I looked into it last. I had a failure today running the pre release version so it may need some tweaking.

If you feel like a PR, I'll merge it otherwise I'll try to get this fixed soon.

**Comment by digitalcoyote** [comment]
Not gonna close this til I have a chance to test it, but I wanted to get it out there as an option (v3.2.5.0  & v4.0.5.0)

**Comment by a-teece** [comment]
@digitalcoyote 4.0.5 is working much better for us on build servers. Thank you for the quick turn around!

Given your comment I'll leave it to you to mark as closed.
