### ISSUE TITLE
Scan returns cryptic error

### ISSUE THREAD

**Issue by marcopierobon** [digitalcoyote/NuGetDefense#27]
**Describe the bug**
Running the build on a net fw project returns this error:
MyProject\packages.config : Warning : NuGetDefense : NVD scan failed with exception: System.ArgumentException: '1.2.9_beta' is not a valid version string.

The project includes both public nugets and private ones, but no direct reference to any package on version 1.2.9_beta is present in the package.config

**To Reproduce**
1. I assume add a package with a non canonical format 
2. Compile

**Expected behavior**
Security vulnerabilities should be detected

**Screenshots**

**Tools (please complete the following information):**
 - IDE: VS2017
 - OS: Windows

**Additional context**
Warning : NuGetDefense : NVD scan failed with exception: System.ArgumentException: '1.2.9_beta' is not a valid version string.
   at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
   at NuGet.Versioning.VersionRange.Parse(String value)
   at NuGetDefense.NVD.Scanner.<>c__DisplayClass8_0.<GetVulnerabilitiesForPackages>b__1(String v)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at NuGetDefense.NVD.Scanner.<>c__DisplayClass8_1.<GetVulnerabilitiesForPackages>b__0(String cve)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuGetDefense.NVD.Scanner.GetVulnerabilitiesForPackages(NuGetPackage[] pkgs, Dictionary`2 vulnDict)

**Comment by digitalcoyote** [comment]
per [Microsoft's Documentation](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning) that is legitmately not a valid version for a NuGet Package. I'm going to try to wrap that in a try catch and log the failure in the build log, report a warning for the version, and remove it from the pacakges list so it is not checked since that couldn't possibly be installed by nuget.

**Comment by digitalcoyote** [comment]
I've got a beta build that should take care of this. Feel free to upgrade to 1.0.6-beta3 on the development feed on myget.org if you need this before release of 1.0.6.0 (likely this weekend).

**Comment by marcopierobon** [comment]
Fantastic!
