### ISSUE TITLE
1.0.6 seems to have broken a scan for me

### ISSUE THREAD

**Issue by dahlsailrunner** [digitalcoyote/NuGetDefense#28]
**Describe the bug**
After updating from v.1.0.5 to 1.0.6 the scan errors out for me.  If I downgrade back to 1.0.5 things work as before, and uninstalling the package removes all errors.

**To Reproduce**
Here is the contents of my packages.config file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.5.0.2" targetFramework="net472" />
  <package id="bootstrap" version="4.4.1" targetFramework="net472" />
  <package id="Effort.EF6" version="2.2.2" targetFramework="net472" />
  <package id="Elasticsearch.Net" version="7.0.0" targetFramework="net472" />
  <package id="EntityFramework" version="6.2.0" targetFramework="net472" />
  <package id="jQuery" version="3.3.1" targetFramework="net472" />
  <package id="jQuery.Validation" version="1.17.0" targetFramework="net472" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.Razor" version="3.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.7" targetFramework="net472" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="2.0.0" targetFramework="net472" />
  <package id="Microsoft.Data.Edm" version="5.8.4" targetFramework="net472" />
  <package id="Microsoft.Data.OData" version="5.8.4" targetFramework="net472" />
  <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.11" targetFramework="net472" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net472" />
  <package id="Modernizr" version="2.8.3" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="11.0.1" targetFramework="net472" />
  <package id="NMemory" version="3.1.0" targetFramework="net472" />
  <package id="NuGetDefense" version="1.0.6" targetFramework="net472" />
  <package id="popper.js" version="1.16.0" targetFramework="net472" />
  <package id="SecurityCodeScan" version="3.5.0.0" targetFramework="net472" developmentDependency="true" />
  <package id="Serilog" version="2.9.0" targetFramework="net472" />
  <package id="Serilog.Enrichers.HttpContextData" version="0.1.3" targetFramework="net472" />
  <package id="Serilog.Formatting.Compact" version="1.0.0" targetFramework="net472" />
  <package id="Serilog.Formatting.Elasticsearch" version="8.0.0" targetFramework="net472" />
  <package id="Serilog.Sinks.Console" version="3.1.1" targetFramework="net472" />
  <package id="Serilog.Sinks.Elasticsearch" version="8.0.0" targetFramework="net472" />
  <package id="Serilog.Sinks.File" version="4.0.0" targetFramework="net472" />
  <package id="Serilog.Sinks.PeriodicBatching" version="2.1.1" targetFramework="net472" />
  <package id="SerilogWeb.Classic" version="5.0.52" targetFramework="net472" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net472" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.5.1" targetFramework="net472" />
  <package id="System.Spatial" version="5.8.4" targetFramework="net472" />
  <package id="WebGrease" version="1.6.0" targetFramework="net472" />
</packages>
```

**Expected behavior**
Was hoping to just have bootstrap not be a reported vulnerability any longer. 

**Screenshots**
This is the build output I got (I first updated the package from 1.0.5 to 1.0.6 and then uninstalled package and installed 1.0.6):
```
1>------ Build started: Project: WiredBrain.CustomerPortal.AspNet, Configuration: Debug Any CPU ------
1>  WiredBrain.CustomerPortal.AspNet -> C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\bin\WiredBrain.CustomerPortal.AspNet.dll
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(3,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(4,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(5,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(6,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(7,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(8,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(9,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(10,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(11,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(12,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(13,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(14,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(15,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(16,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(17,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(18,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(19,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(20,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(21,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(22,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(23,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(24,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(25,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(26,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(27,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(28,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(29,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(30,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(31,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(32,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(33,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(34,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(35,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(36,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config(37,4): warning : is not a valid NuGetVersion and is being ignored. See 'https://docs.microsoft.com/en-us/nuget/concepts/package-versioning' for more info on valid versions
1>C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\packages.config : error : NuGetDefense : OSS Index scan failed with exception: System.AggregateException: One or more errors occurred. (The JSON value could not be converted to NuGetDefense.OSSIndex.ComponentReport[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.)
1>   ---> System.Text.Json.JsonException: The JSON value could not be converted to NuGetDefense.OSSIndex.ComponentReport[]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
1>     at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
1>     at System.Text.Json.JsonSerializer.HandleStartObject(JsonSerializerOptions options, ReadStack& state)
1>     at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
1>     at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
1>     at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
1>     at NuGetDefense.OSSIndex.Scanner.GetReportsForPackagesAsync(NuGetPackage[] pkgs)
1>     --- End of inner exception stack trace ---
1>     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
1>     at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
1>     at System.Threading.Tasks.Task`1.get_Result()
1>     at NuGetDefense.OSSIndex.Scanner.GetVulnerabilitiesForPackages(NuGetPackage[] pkgs, Dictionary`2 vulnDict)
1>C:\temp\wired-brain-aspnet\packages\NuGetDefense.1.0.6\build\nugetdefense.targets(10,5): error MSB3073: The command "dotnet "C:\temp\wired-brain-aspnet\packages\NuGetDefense.1.0.6\build\..\tools\netcoreapp3.1\NuGetDefense.dll" "C:\temp\wired-brain-aspnet\WiredBrain.CustomerPortal.AspNet\WiredBrain.CustomerPortal.AspNet.csproj" " exited with code -1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Tools (please complete the following information):**
 - IDE: VS 2019
 - OS: Win 10 Pro

**Additional context**

**Comment by dahlsailrunner** [comment]
This does not require an urgent fix from my perspective, as I can ignore bootstrap in the 1.0.5 version, but would be good to resolve for sure.  Let me know if I can help in any way.

**Comment by digitalcoyote** [comment]
apparently x.Attribute("Version") is case sensitive and is returning null for every package. This needs to be corrected, and it needs a different error message if the version attribute is not found.

**Comment by digitalcoyote** [comment]
I'm still doing some tests on this, but I'm fairly certain I have it corrected in that commit.

**Comment by digitalcoyote** [comment]
I missed the OSSIndex Issue, Reopening (this is what I get for trying to fix code this late)

**Comment by dahlsailrunner** [comment]
All good - and I get it haha.  Let me know if I can check or help with anything.

**Comment by digitalcoyote** [comment]
Crazy busy lately, so I haven't had a chance to work on the OSSIndex error. I'm going to try to add the raw response to the error message to make it easier to ell what's going on, but if you could get a copy of the response body (and potentially the request body), it would likely help once I get a chance to look into this. Fiddler by Telerik is a free tool that can capture this if you don't want to debug it.

**Comment by dahlsailrunner** [comment]
I've fallen into same busy trap, I think.  I'll see if I can review this weekend.  It's not a show-stopper for me for sure.

**Comment by dahlsailrunner** [comment]
I'll see if I can have a look later on - but I spent an hour or so this morning and still haven't been able to run/repro the issue with the locally-pulled code.  I wiped the VulnerabilityData.bin file and now just running the code seems to be having trouble getting it back in place.  Not sure what's going on - and family demands are pulling me away.  I'll see if I can get back to it in a bit.

**Comment by digitalcoyote** [comment]
I generate the initial VulnerabilityData.bin using NuGetDefense.NVD project's console app. Considering I don't distribute it in that package, it should probably be  moved into the main NuGetDefense project to make builds easier. I'm in the process of moving amidst the higher workload from work. In about a month, I'll be freed up to out more time into this issue again.

**Comment by digitalcoyote** [comment]
I finally ran into this issue in a reproduceable way. I expect that once I am able to get to work on it, it should be fairly easy to fix.

**Comment by dahlsailrunner** [comment]
That's awesome and I really appreciate the follow up.  As I imagine it is with you, things have been a little hectic for me lately so this is super helpful.  This issue is not blocking me but will be great to have resolved.

**Comment by digitalcoyote** [comment]
1.0.7.2 may fix this issue I'll wait for confirmation before closing this issue.

**Comment by dahlsailrunner** [comment]
Confirmed!  1.0.7.2 does indeed fix the issue I was seeing!  Thanks a lot for taking care of this.
