### ISSUE TITLE
NuGetDefense.Tool throws an exception on a `Solution Items` project from the solution file

### ISSUE THREAD

**Issue by rajbos** [digitalcoyote/NuGetDefense#58]
**Describe the bug**
NuGetDefense.Tool throws an exception on a `Solution Items` project from the solution file.

**To Reproduce**
1. Have a project file with a `Solution Items` folder 
2. Install the tool: `dotnet tool install NuGetDefense.Tool -g`
3. Run the tool: `nugetdefense .\MySolution.sln Release`
4.  Fails with exception message

## Example project file part that causes this: 
```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{DAC32E4B-F605-4584-A629-554E7523B1FD}"
	ProjectSection(SolutionItems) = preProject
		.editorconfig = .editorconfig
		.gitlab-ci.yml = .gitlab-ci.yml
		common\GenerateBuildInfo.sh = common\GenerateBuildInfo.sh
		README.md = README.md
	EndProjectSection
EndProject
```

## Exception:
```
`dotnet list` Errors:

`dotnet list` Errors:

`dotnet list` Errors:

: Error : Encountered a fatal exception while checking for Dependencies in . Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\RobBos\source\repos\MyRepoName\Solution Items'.
File name: 'C:\Users\RobBos\source\repos\MyRepoName\Solution Items'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri)
   at ByteDev.DotNet.Project.DotNetProject.Load(String projFilePath)
   at NuGetDefense.Program.LoadMultipleProjects(String TopLevelProject, String[] projects, Boolean specificFramework, String targetFramework, Boolean solutionFile) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense/Program.cs:line 193   at NuGetDefense.Program.Main(String[] args) in /home/codingcoyote/Code/NuGetDefense/Src/NuGetDefense/Program.cs:line 73
```

**Expected behavior**
Not fail :-). Perhaps detect the type of project and skip it.

**Screenshots**

**Tools (please complete the following information):**
 - dotnet global toos
 - Windows 10 19042

**Additional context**
Found the link to the source code here: 
https://github.com/digitalcoyote/NuGetDefense/blob/4f01373b1bddb84688d5d239ca1436fdf03cffb8/Src/NuGetDefense/Program.cs#L193

Unfortunately you only push in the names of the projects to this method. 
I see three options:
1. Eat up the exception on Project load and log it
2. Only load valid projects on [solution file load](https://github.com/digitalcoyote/NuGetDefense/blob/4f01373b1bddb84688d5d239ca1436fdf03cffb8/Src/NuGetDefense/Program.cs#L66)
3. Add option to skip certain projects during the analysis

**Comment by rajbos** [comment]
Seems like I found how to fix this. Setting up a PR for this fix

**Comment by digitalcoyote** [comment]
v2.1.1-pre0001 has the fix for this, but I didn't have time on lunch to test the packaging, so I threw it in a pre-release.
