### ISSUE TITLE
System.ArgumentException during scan

### ISSUE THREAD

**Issue by SH-ZorgNed** [digitalcoyote/NuGetDefense#71]
**Describe the bug**
When scanning a project I get the following warning:
PS C:\tfs\XXX> NugetDefense -p XXX.csproj --settings-file Nugetdefense.json
C:\tfs\XXX\packages.config : Warning : NuGetDefense : GitHub Advisory Database scan failed with exception: System.ArgumentException: '= 4.5.0' is not a valid version string.
   at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
   at NuGetDefense.GitHubAdvisoryDatabase.Scanner.GetVulnerabilitiesForPackages(IEnumerable`1 pkgs, Dictionary`2 vulnDict)

in package.config there are 2 packages with version 4.5.0 and both exists in NuGet:
<package id="System.ValueTuple" version="4.5.0" targetFramework="net48" />
<package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net48" />

**To Reproduce**
Running: NugetDefense -p XXX.csproj --settings-file Nugetdefense.json

**Expected behavior**
No exception or clear description which package is the issue

**Tools (please complete the following information):**
nugetdefense --version
3.0.0+b84579b29797be7baa5eb366d8759bdff1710b41

**Comment by digitalcoyote** [comment]
It looks like it's parsing the version out incorrectly since it included the = sign. I'll take a look at this as soon as I get home to my desk.

**Comment by digitalcoyote** [comment]
I couldn't reproduce this so far. Any of the following would be helpful (unless it's sensitive data):

- Target Framework (ex .Net 4.6.1, .Net 6, etc)
- Package.json or Package References list from the csproj file
- Type of project (SDK style, xproj or legacy .Net Framework project)

If you have anything else you think might be useful (even a copy of the request sent to GitHub (with any sensitive info removed) I'd be happy to take a second look.

**Comment by SH-ZorgNed** [comment]
Tanks for looking into it.

I have attached package.config (had to upload it as txt file) and from the csproj file:

<Project ToolsVersion="Current" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <SchemaVersion>2.0</SchemaVersion>
    <OutputType>Library</OutputType>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <RuntimeIdentifier>win</RuntimeIdentifier>

It is a legacy .net framework project. It is a very old project with .net version upgraded over time
[packages.config.txt](https://github.com/digitalcoyote/NuGetDefense/files/8122286/packages.config.txt)
.

**Comment by digitalcoyote** [comment]
Ok, so it turns out that it wasn't parsing the response from GitHub correctly for exact versions. I'll try to push a fixed version out tonight

**Comment by digitalcoyote** [comment]
Turns out there is another issue. I'll be looking into that one tomorrow. (an extra comma in the parsed version).
